version: '3.8'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: news_db
    ports:
      - "3306:3306"
  web:
    build:
      context: .
    environment:
      - DB_HOST=db
      - DB_NAME=news_db
      - DB_USER=root
      - DB_PASS=password
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db